#!/bin/sh

miphone_addr="192.168.1.8"
#miphone_addr="192.168.1.25"
mipad_addr="192.168.1.12"

pictures_dir="$(xdg-user-dir PICTURES)"/miphone
videos_dir="$(xdg-user-dir VIDEOS)"/miphone
mipad_dir="$HOME"/Documents/backup/mipad
music_dir="$(xdg-user-dir MUSIC)"
# trailing slash - do not create dir
# in this case I want it to create dir if
# not present already

# assume that simple sshd in running on android device
# TODO: add error message when connection fails
# rsync -rtvzP root@192.168.1.8:/sdcard/DCIM/Camera .

# this ping actually does not do what I wanted it to do
#ping -W 0.5 -c1 "$miphone_addr" 2>&1 > /dev/null
echo phone

if [ $? = 0 ];
then
# maybe make this into a function
    rsync -rtvzP root@"${miphone_addr}":/sdcard/DCIM/Camera \
	  --exclude="*.mp4" --exclude="Raw" --exclude=".trashed*" "$pictures_dir"
    rsync -rtvzP root@"${miphone_addr}":/sdcard/Pictures \
	  --exclude=".*" "$pictures_dir"
	rsync -rtvzP --exclude=".trashed*" root@"${miphone_addr}":/sdcard/DCIM/Screenshots "$pictures_dir"
	# also copy music because I download a lot of on my phone
	# through newpipe
	rsync -rtvzP root@"${miphone_addr}":/sdcard/Download/*.m4a "$music_dir"
	# if it copies Videos as well from DCIM or whatever, then copy videos
	# I received as a message as well, because they are apparently stored
	# in a different directory
	# I do not want to back movies up at this point
	# rsync -rtvzP root@"${miphone_addr}":/sdcard/Movies \
	#      --exclude=".*" "$videos_dir"
	rsync -rtvzP root@"${miphone_addr}":/sdcard/DCIM/Camera/*.mp4 \
	      "$videos_dir"/Camera
fi

ping -W 0.5 -c1 "$mipad_addr" 2>&1 > /dev/null
if [ $? = 0 ];
then
	rsync -rtvzP root@"${mipad_addr}":/sdcard/DCIM/Camera "$mipad_dir"
	rsync -rtvzP root@"${mipad_addr}":/sdcard/Pictures "$mipad_dir"
	rsync -rtvzP root@"${mipad_addr}":/sdcard/DCIM/Screenshots "$mipad_dir"
fi
