#!/bin/sh
#cap=$(cat /sys/class/power_supply/BAT0/capacity)
#echo "$cap%"
log_dir=${XDG_DATA_HOME-:$HOME/.local/share}/batstat
test -d "$log_dir" || mkdir -p "$log_dir"
while true
do
	echo "$(date +'%F %H:%M:%S') - $(acpi)" | tee -a "$log_dir"/log
	sleep 30
done
