#!/bin/sh
#cap=$(cat /sys/class/power_supply/BAT0/capacity)
#echo "$cap%"
log_dir=${XDG_DATA_HOME-:$HOME/.local/share}/batstat
test -d "$log_dir" || mkdir -p "$log_dir"
while true
do
	acpi >> "$log_dir"/log
	sleep 1
done
