#!/bin/sh

dunstctl close-all
xbacklight -set $1 || xbacklight -inc 10
notify-send -c brightness -t 1500 "Brightness increased"\
 "Current brightness $(xbacklight -get | cut -d'.' -f1)"
# I have to leave whitespace in the beginning or else the
# formatting is not correct

