#!/bin/sh

dunstctl close-all
alt_bl=$(brightnessctl -d intel_backlight | grep -o --color=never "[0-9]*%" | tr -d %)
brightnessctl -d intel_backlight set "$(($alt_bl + 10))%"
notify-send -c brightness -t 1500 "Brightness increased"\
 "Current brightness $(($alt_bl + 10))"
# I have to leave whitespace in the beginning or else the
# formatting is not correct

