#!/bin/sh

# or something similar
device_label="Samsung240GB0921"

device_name="samsung_usb"
# no trailing slash here, might change later
mount_point=/media/"$USER"/usb_drive1

# first argument is label and second is the name
# for cryptsetup and the last one is mount point
open_device() {
# before I could do this I realised that ext4 on
# encrypted volume of course did not have access to it
# yet so I had to run this command to also add label to
# encrypted partition this only works for luks2 headers
# but I do not care as of now
# sudo cryptsetup config /dev/sda1 --label Samsung240GB0921
    test -b /dev/disk/by-label/"$1" || exit 1
    test -b /dev/mapper/"$2" || (sudo cryptsetup\
	open /dev/disk/by-label/"$1" "$2" && sudo fsck /dev/mapper/"$2" &&\
	sudo mount -t ext4 /dev/mapper/"$2" "$3")
}

make_copy() {
# the slash is important, I just want the contents
# of the directory
# delete so it is just a snapshot and does not contain
# duplicates if the files were moved/renamed whatever
# trailing slash because variable does not have it
# exclude dreary emacs nonsense
    bnf ls-files > /tmp/file_list
    rsync -rtvzP --files-from=/tmp/file_list "$HOME"/.local/bin/ "$mount_point"/bin_bak --delete --delete-excluded
# I do not know it if there is a way that could avoid creating the file
# but examples I reviewed also used it so I do not care as it will be
# deleted after reboot anyway
    cnf ls-files > /tmp/file_list
    rsync -rtvzP --files-from=/tmp/file_list "$XDG_CONFIG_HOME"/\
	/media/thea/usb_drive1/conf_bak --delete
# it seems that delete doe snot work with files-from
# I will need to debug this later because the unwanted files
# remained so I clearly made a mistake
# only get the useful files that are in the repo, cnf is my local command as per
# https://news.ycombinator.com/item?id=11071754

# maybe here also include iso but I am not so sure
# as they can also be in the dl/software/images folder
    rsync -rtvzP --exclude vms --exclude backup --exclude configuration\
	--exclude executables\
	"$HOME"/Documents/ /media/thea/usb_drive1/doc_bak\
	--delete --delete-excluded

    rsync -rtvzP --exclude="*~" "$HOME"/Journals/ "$mount_point"/jour_bak\
	--delete --delete-excluded
}


open_device "$device_label" "$device_name" "$mount_point"

make_copy

# the last thing to consider would be phone/tablet backups
# as they mostly consist of photos and music which should be
# moved to their respective folders on my system not sit
# forever so I should make another program for taking care of that
