#!/bin/sh

font_name="Hack Regular Nerd Font Complete"
lines=10

wall_dir=$(xdg-user-dir WALLPAPERS)
wall_dir_alt=$(echo $wall_dir | sed s,$HOME,'$HOME',)

sel=$(find "$wall_dir" -type f -print0 |
	  # slow with sh -c but without basename did not work
	  xargs -0 -I {} sh -c 'echo $(basename -a "{}")' |
	  rofi -dmenu -i -l "$lines" -fn "$font_name")
# TODO:
# something to consider? sel=$(ffile "$wall_dir")

if [ -z "$sel" ];
then
    echo "Nothing was chosen"
    exit 0
fi

echo $sel

feh --bg-fill --no-fehbg "$wall_dir"/"$sel" || {
    echo "Cannot set $sel as wallpaper";
    exit 1; }

sel="$wall_dir_alt"/"$sel"

# set in XDG_CONFIG_HOME/user-dirs.dirs
env_var_file=$(xdg-user-dir SHVARS)

prev=$(grep "WALLPAPER" "$env_var_file" | cut -d= -f2)
sed -i "s,$prev,$sel,g" "$env_var_file"
